FROM ghcr.io/cyber-dojo-languages/javascript-node:04531dc
LABEL maintainer=jon@jaggersoft.com
LABEL maintainer=daniel@bartholomae.name

RUN mkdir /etc/ts
WORKDIR /etc/ts
COPY package.json .
RUN npm install

