FROM cyberdojofoundation/javascript-node:29eb2ed
LABEL maintainer=jon@jaggersoft.com
LABEL maintainer=daniel@bartholomae.name

RUN mkdir /etc/ts
WORKDIR /etc/ts
COPY package.json .
RUN npm install

COPY red_amber_green.rb /usr/local/bin
